version: "3"
services:
  database:
    image: postgres:17.2
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}