name: PR
description: Validate PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  install_deps:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Use CI action
        uses: ./.github/workflows/ci

  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
